### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Mirsario/Minecraft-CameraOverhaul#39]
https://mclo.gs/eIJgQXm

**Comment by Mirsario** [comment]
Looks like in 3572102 I broke a [compatibility patch](https://github.com/enjarai/do-a-barrel-roll/blob/main/fabric/src/main/java/nl/enjarai/doabarrelroll/compat/cameraoverhaul/mixin/CameraSystemMixin.java?ts=4) from `Do a Barrel Roll`, as I didn't know that anyone's referencing these methods.

@enjarai ^
Mind updating the mixins on your side? These new method signatures should stay the same for a long time from now at least.
If Java had value types - I would instead do a single separate and more reliable method for modifying/calculating to-be-used config instances, so that you could inject into those. Although that could be even less convenient for you due to the need to reference the config's type.
¯\\\_(ツ)_/¯

**Comment by enjarai** [comment]
Ah I see, thanks for letting me know, I'll update it shortly. 😄 

Compat mixins into other mods are inherently quite invasive and liable to breaking, so I don't mind updating them every once in a while. I wonder if a mixin plugin can be used to send clearer error messages in these situations though...

**Comment by enjarai** [comment]
Pretty sure I fixed my mixin, but I can't get the new version of your mod to work in my 1.19.3 dev env. It crashes with a `NoClassDefFound` for `Vec3f` when loading a world. I don't think this is due to anything on my side, do you know whats up here?

[crash-2023-01-01_17.43.55-client.txt](https://github.com/Mirsario/Minecraft-CameraOverhaul/files/10329111/crash-2023-01-01_17.43.55-client.txt)

**Comment by Mirsario** [comment]
1.19.3 should use V2 math abstraction, but you're getting a crash on the V1 fallback. Need latest.log instead.

**Comment by enjarai** [comment]
Ah okay, here you go:

[latest.log](https://github.com/Mirsario/Minecraft-CameraOverhaul/files/10329134/latest.log)

**Comment by Mirsario** [comment]
@enjarai Seems like you have outdated clothconfig, but that wouldn't be related to the crash. Could it be that your dev environment has differently named runtime member/type names, which screws with reflection? I've made a build with more logging - if it logs that the zero-indexed math abstraction "returned nothing" and if it works fine in non-dev env - then what I said is the case. Reflection becoming an even bigger pain that it already is is a scary thought.

[CameraOverhaul-1.4.0-extralogging.zip](https://github.com/Mirsario/Minecraft-CameraOverhaul/files/10329231/CameraOverhaul-1.4.0-extralogging.zip)

**Comment by enjarai** [comment]
Here are logs from my dev env and a fresh production instance, everything seems to work fine in prod. I'll assume I'm safe to push out my mixin fix, but it looks like you have an encounter with the joys of reflection to work out lmao. Good luck with that, and lmk if you need me to test any more builds.

[latest-dev.log](https://github.com/Mirsario/Minecraft-CameraOverhaul/files/10329247/latest-dev.log)
[latest-prod.log](https://github.com/Mirsario/Minecraft-CameraOverhaul/files/10329249/latest-prod.log)

**Comment by Mirsario** [comment]
@Aces-and-Jacks Update `Do a Barrel Roll` to `2.3.4`.

**Comment by Aces-and-Jacks** [comment]
got it, thanks. Saw it was updated just forgot to close
