### ISSUE TITLE
Implement a ModMenu configuration screen

### ISSUE THREAD

**Issue by Mirsario** [Mirsario/Minecraft-CameraOverhaul#4]
I have attempted this, and found it to be rather painful. I couldn't find any good documentation.

**Comment by altrisi** [comment]
ModMenu config screens aren't any kind of extensive API to allow for editing config files or values. In ModMenu, the implementation you make of their interface should just open an existing screen. Therefore, you need to provide it with an actual Screen that allows to modify your config values, and shows any other related information.

The common way this is tackled is by using some config API, such as [cloth-config](https://github.com/shedaniel/cloth-config) or [cotton-config](https://github.com/CottonMC/cotton/wiki/Config-Files). Those provide a config screen ready for you to plug into ModMenu.

Since I've seen you try to keep this as less loader dependant as possible, cloth-config has a Forge version for the same API, which may be desired. You can find their docs [here](https://shedaniel.gitbook.io/cloth-config/). If you want to make the config creation as simple as possible, in those docs you can go directly to the auto-config section, which saves and loads the values by itself (although it's a bit more bulky, and since you already have a load method, it may not be necessary).

The problem is of course that by adding those you basically need to include or require extra libraries in your mod (the config things apis would be included, then FAPI would be required, etc), but I think making a custom config screen is a bit outside of the scope of this mod.

**Comment by altrisi** [comment]
If you want I can try to implement one in a PR using cloth-config.

**Comment by Mirsario** [comment]
Would it possible to embed both cloth-config and fabric-api into this mod? I believe I heard that it's possible somewhere.

**Comment by altrisi** [comment]
Cloth-config is intended to be embedded when being used. FAPI can also be embedded, although that is thought to be used only in case you don't need many modules (not sure how many does cloth-config use, it doesn't declare it directly). Should be possible.

~Not sure what is the current Gradle name for it, since the old ones I knew I think are now deprecated.~

**Comment by altrisi** [comment]
Wait actually cloth-config has it in their docs, it's still `include`.

Therefore, something like:

```gradle
	include "net.fabricmc.fabric-api:fabric-resource-loader-v0:${project.fabric_resource_loader_v0_version}"
```

would include the resource-loader module of FAPI into the final JAR (as JiJ / Jar-in-Jar).

**Comment by Mirsario** [comment]
Then it sounds fine to use that.

> If you want I can try to implement one in a PR using cloth-config.
I would definitely appreciate that!

**Comment by altrisi** [comment]
Since I'm not 100% sure of what each config field means, I'll make the PR with empty texts.

You'll need to add a proper `name` and `tooltip` for each.
